body:
  - type: input
    attributes:
      label: Title
      description: A clear and concise title for the feature request
      placeholder: Cool new idea i want in the app
      validations:
      required: true

  - type: input
    attributes:
      label: information
      description: Describe the feature you'd like to see in the app with long term
      placeholder: This feature will make the app user more friendly
      validations:
        required: true
