body:
  - type: textarea
    attributes:
      label: information
      description: Describe the feature you'd like to see in the app with long term
      placeholder: This feature will make the app user more friendly
    validations:
      required: true

  - type: textarea
    attributes:
      label: benefits for others [for advance and normal users]
      description: Describe the benefits of the feature for the users
      placeholder: This feature will be used by advance and normal people's like ...
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Priority
      description: How much priority would you like to give to this feature?
      options:
        - 1 ⭐
        - 2 ⭐
        - 3 ⭐
        - 4 ⭐
        - 5 ⭐
    validations:
      required: true

  - type: textarea
    attributes:
      label: edit
      description: If you need to edit then type here don't edit it.
      placeholder: "[1/1/2025]I want to change where the part is shown is not what i meant because..."
    validations:
      required: false
