name: Report an issue
description: Report a MessengerCraft issue.
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        This template is for reporting bugs within MessengerCraft. If you have a question, see our [GitHub Discussions](https://github.com/adharshgamingyt/MessengerCraft/discussions/categories/help)

        Feature requests should opened in [feature request](https://github.com/adharshgamingyt/MessengerCraft/issues) and also opened in [discussions](https://github.com/adharshgamingyt/MessengerCraft/discussions/categories/ideas)

        Before opening a new issue, please do a [search](https://github.com/adharshgamingyt/MessengerCraft/issues) of existing issues and :+1: upvote the existing issue instead. This will result in a quicker resolution.

        If you need any help please contact us:
        - Start a discussion in the ["Help"](https://github.com/adharshgamingyt/MessengerCraft/discussions/categories/help)
        - React our support team from the website.

  - type: input
    attributes:
      label: Bug Title
      description: A clear and concise title that describes the bug
    validations:
      required: true

  - type: textarea
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the bug. [optional]

  - type: textarea
    attributes:
      label: Provide device information
      description: Provide information about the device you are using.
      placeholder: |
        - Device: [e.g. samsung galaxy s24]
        - OS: [e.g. Andriod 14]
        - Browser: [e.g. Chrome, Safari]
        - Version: [e.g. 22]
        - platform: [e.g. mobile app, desktop app, website]

  - type: dropdown
    attributes:
      label: Which area(s) are affected? (Select all that apply)
      multiple: true
      options:
        - Full app
        - Chat
        - Profile
        - User
        - ui [e.g. buttons, text, etc] user interface
        - story
        - privacy
        - security
        - other
    validations:
      required: true

  - type: input
    attributes:
      label: Expected behavior
      description: What that need to do?
      placeholder: |
        [e.g. It need to change the color of the button]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here. [e.g. screenshots, recorded video, etc]

  - type: markdown
    attributes:
      value: |
        This is for advance users only!
        if you know little coding then send the information about errors in dev tools / console.

  - type: textarea
    attributes:
      label: Advance logs
      description: console error etc
