name: Feature request
description: Suggest a new feature or improvement for MessengerCraft.
body:
  - type: markdown
    attributes:
      value: |
        This template is for suggesting feature to add within MessengerCraft. If you have a question, see our [GitHub Discussions](https://github.com/adharshgamingyt/MessengerCraft/discussions/categories/help)

        Feature requests should opened in [feature request](https://github.com/adharshgamingyt/MessengerCraft/issues) and also opened in [discussions](https://github.com/adharshgamingyt/MessengerCraft/discussions/categories/ideas)

        Before opening a new issue, please do a [search](https://github.com/adharshgamingyt/MessengerCraft/issues) of existing issues and :+1: upvote the existing issue instead. This will result in a quicker resolution.

        If you need any help please contact us:
        - Start a discussion in the ["Help"](https://github.com/adharshgamingyt/MessengerCraft/discussions/categories/help)
        - React our support team from the website.

  - type: input
    id: problem_description
    attributes:
      label: Problem Description
      description: A clear and concise description of what the problem is.
      placeholder: Describe the problem...

  - type: markdown
    attributes:
      value: |
        **Describe the solution you'd like**
        A clear and concise description of what you want to happen.

  - type: input
    id: solution_description
    attributes:
      label: Solution Description
      description: A clear and concise description of what you want to happen.
      placeholder: Describe the solution...

  - type: markdown
    attributes:
      value: |
        **Describe alternatives you've considered**
        A clear and concise description of any alternative solutions or features you've considered.

  - type: input
    id: alternatives_description
    attributes:
      label: Alternatives Description
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Describe the alternatives...

  - type: markdown
    attributes:
      value: |
        **Additional context**
        Add any other context or screenshots about the feature request here.

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Add any other context...
